//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.1
//     from Assets/Sources/Input/TsunamiInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TsunamiInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TsunamiInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""TsunamiInput"",
    ""maps"": [
        {
            ""name"": ""Movement"",
            ""id"": ""191faeca-a642-41e3-af9c-97c32332c609"",
            ""actions"": [
                {
                    ""name"": ""Turn"",
                    ""type"": ""Value"",
                    ""id"": ""9ed1c02e-c297-41ee-97c8-9c3f7dc2b64e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TurnTouch"",
                    ""type"": ""Value"",
                    ""id"": ""46681c96-e77e-4072-9327-4b543f7bad54"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Touch"",
                    ""type"": ""Button"",
                    ""id"": ""600e6605-686c-4f12-9443-085e5eee65ac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""4901806f-8765-4885-b2b3-acd53036a6fc"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""4a14042e-2543-43b6-b6a6-0ab440d6f00d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""768e5f36-0887-46a6-acc0-b8e534e3e98f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""bfe54848-94db-43d3-8eee-b52efca28747"",
                    ""path"": ""<Touchscreen>/position/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TurnTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""512c7220-28b1-4420-b3a7-9ddb92444b73"",
                    ""path"": ""<Touchscreen>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Movement
        m_Movement = asset.FindActionMap("Movement", throwIfNotFound: true);
        m_Movement_Turn = m_Movement.FindAction("Turn", throwIfNotFound: true);
        m_Movement_TurnTouch = m_Movement.FindAction("TurnTouch", throwIfNotFound: true);
        m_Movement_Touch = m_Movement.FindAction("Touch", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Movement
    private readonly InputActionMap m_Movement;
    private IMovementActions m_MovementActionsCallbackInterface;
    private readonly InputAction m_Movement_Turn;
    private readonly InputAction m_Movement_TurnTouch;
    private readonly InputAction m_Movement_Touch;
    public struct MovementActions
    {
        private @TsunamiInput m_Wrapper;
        public MovementActions(@TsunamiInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Turn => m_Wrapper.m_Movement_Turn;
        public InputAction @TurnTouch => m_Wrapper.m_Movement_TurnTouch;
        public InputAction @Touch => m_Wrapper.m_Movement_Touch;
        public InputActionMap Get() { return m_Wrapper.m_Movement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MovementActions set) { return set.Get(); }
        public void SetCallbacks(IMovementActions instance)
        {
            if (m_Wrapper.m_MovementActionsCallbackInterface != null)
            {
                @Turn.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnTurn;
                @Turn.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnTurn;
                @Turn.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnTurn;
                @TurnTouch.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnTurnTouch;
                @TurnTouch.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnTurnTouch;
                @TurnTouch.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnTurnTouch;
                @Touch.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnTouch;
                @Touch.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnTouch;
                @Touch.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnTouch;
            }
            m_Wrapper.m_MovementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Turn.started += instance.OnTurn;
                @Turn.performed += instance.OnTurn;
                @Turn.canceled += instance.OnTurn;
                @TurnTouch.started += instance.OnTurnTouch;
                @TurnTouch.performed += instance.OnTurnTouch;
                @TurnTouch.canceled += instance.OnTurnTouch;
                @Touch.started += instance.OnTouch;
                @Touch.performed += instance.OnTouch;
                @Touch.canceled += instance.OnTouch;
            }
        }
    }
    public MovementActions @Movement => new MovementActions(this);
    public interface IMovementActions
    {
        void OnTurn(InputAction.CallbackContext context);
        void OnTurnTouch(InputAction.CallbackContext context);
        void OnTouch(InputAction.CallbackContext context);
    }
}
